-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 13:49:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grading_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grading_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grading_system` DEFAULT CHARACTER SET utf8 ;
USE `grading_system` ;

-- -----------------------------------------------------
-- Table `grading_system`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grading_system`.`credentials` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grading_system`.`users` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `role` SMALLINT NOT NULL,
  `credentials_id` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `credentials_id_UNIQUE` (`credentials_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `credentials_id`
    FOREIGN KEY (`credentials_id`)
    REFERENCES `grading_system`.`credentials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `grading_system`.`credentials` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_system`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grading_system`.`subjects` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT(1000) NULL,
  `semester` INT NOT NULL,
  `supervisor_id` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supervisor_idx` (`supervisor_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `supervisor`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `grading_system`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_system`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grading_system`.`projects` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(1000) NOT NULL,
  `deadline` DATE NOT NULL,
  `subject_id` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `grading_system`.`subjects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_system`.`submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grading_system`.`submissions` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `code` LONGTEXT NOT NULL,
  `date` DATE NOT NULL,
  `grade` INT NULL,
  `comment` TEXT(200) NULL,
  `submitee_id` SMALLINT NOT NULL,
  `project_id` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `project_id_idx` (`project_id` ASC) VISIBLE,
  INDEX `submitee_id_idx` (`submitee_id` ASC) VISIBLE,
  CONSTRAINT `submitee_id`
    FOREIGN KEY (`submitee_id`)
    REFERENCES `grading_system`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `grading_system`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_system`.`user_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grading_system`.`user_subject` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT NOT NULL,
  `subject_id` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `grading_system`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subject_id1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `grading_system`.`subjects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
